version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://api:5001/api
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
    networks:
      - todo_network

networks:
  todo_network:
    external: true
    name: to-do-api_todo_network 